server:
  port: 18880


spring:


  datasource:
    url: jdbc:h2:file:./data/joonmattang
    username: min
    password: min!123
    driver-class-name: org.h2.Driver

  # 개발에 사용하는 옵션(create - table를 매번 새로 만듬, update - 변경된 부분만 업데이트), 리얼에서는 validate
  # update 사용시 주의가 필요함. 컬럼이 삭제 되었을때, 반영하지 못해 쓰레기 값이 남을 수 있음. 컬럼 명이 바꼈을때 반영되지 않음. 툴을 통한 관리 필요.
  jpa:
    hibernate:
      ddl-auto: create

    # sql을 보여줌
    show-sql: true

    # sql format pretty
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true